name: Trigger auto deployment for auth-api

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/auth-api-AutoDeployTrigger-86f89283-8175-4f5d-b2aa-6d9b37be0d99.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AUTHAPI_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AUTHAPI_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AUTHAPI_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: docker.io
          registryUsername: ${{ secrets.AUTHAPI_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.AUTHAPI_REGISTRY_PASSWORD }}
          containerAppName: auth-api
          resourceGroup: gestion-escolar
          imageToBuild: asinaluisa/auth-api:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


